-- ============================================================
-- Standalone: let admin delete a service even if old bookings
-- reference it. Changes bookings.service_id FK to ON DELETE SET NULL
-- so historical bookings keep their data but lose the service ref.
-- Run in Supabase SQL Editor. Idempotent.
-- ============================================================

-- Drop existing FK (name is generated by Postgres; look it up)
DO $$
DECLARE fk_name TEXT;
BEGIN
  SELECT conname INTO fk_name
  FROM pg_constraint
  WHERE conrelid = 'public.bookings'::regclass
    AND contype = 'f'
    AND pg_get_constraintdef(oid) LIKE '%REFERENCES services(id)%';

  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE bookings DROP CONSTRAINT %I', fk_name);
  END IF;
END$$;

-- Recreate with ON DELETE SET NULL
ALTER TABLE bookings
  ADD CONSTRAINT bookings_service_id_fkey
  FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL;

-- Same treatment for staff_id, in case you remove staff later
DO $$
DECLARE fk_name TEXT;
BEGIN
  SELECT conname INTO fk_name
  FROM pg_constraint
  WHERE conrelid = 'public.bookings'::regclass
    AND contype = 'f'
    AND pg_get_constraintdef(oid) LIKE '%REFERENCES staff(id)%';

  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE bookings DROP CONSTRAINT %I', fk_name);
  END IF;
END$$;

ALTER TABLE bookings
  ADD CONSTRAINT bookings_staff_id_fkey
  FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE SET NULL;

-- Verify
SELECT conname, pg_get_constraintdef(oid)
FROM pg_constraint
WHERE conrelid = 'public.bookings'::regclass AND contype = 'f';
